import { Theme } from './types';

export const DEFAULT_MARKDOWN = `# 欢迎使用公众号排版神器

这是一个 **所见即所得** 的 Markdown 编辑器，专为微信公众号设计。

## ✨ 主要功能

1. **多主题切换**：点击上方工具栏切换不同风格。
2. **AI 智能辅助**：利用 Gemini 模型润色文章、生成标题。
3. **一键复制**：直接复制渲染后的格式，完美粘贴到公众号后台。

## 🎨 样式展示

### 引用样式
> 这是一个引用段落。设计的本质是解决问题，而不仅仅是美化外观。

### 列表样式
*   简洁的界面
*   快速的响应
*   优雅的排版

### 代码块
\`\`\`javascript
const sayHello = () => {
  console.log("Hello, WeChat!");
};
\`\`\`

开始你的创作吧！
`;

// Standard WeChat Font Stack
const WECHAT_FONT_FAMILY = "-apple-system-font, BlinkMacSystemFont, 'Helvetica Neue', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI', 'Microsoft YaHei', Arial, sans-serif";
const SERIF_FONT_FAMILY = "'Songti SC', 'SimSun', 'Times New Roman', Times, serif";
const MONO_FONT_FAMILY = "Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace";

// Common base styles - "Style Sinking" Strategy
const baseText = {
  lineHeight: '1.75',
  letterSpacing: '0.05em',
  fontSize: '16px',
  textAlign: 'justify' as const,
  color: '#333333',
  margin: '0 0 1.5em 0',
  clear: 'both' as const,
  fontFamily: WECHAT_FONT_FAMILY,
  overflowWrap: 'break-word' as const,
};

// Explicit styles for LI elements
const baseLi = {
  fontSize: '16px',
  lineHeight: '1.75',
  color: '#333333',
  fontFamily: WECHAT_FONT_FAMILY,
  marginBottom: '8px',
  textAlign: 'justify' as const,
};

// Common list container styles
const baseList = {
  margin: '0 0 1.5em 0',
  paddingLeft: '10px', 
  listStylePosition: 'inside' as const,
  listStyleType: 'disc', // Default fallback
};

export const THEMES: Theme[] = [
  {
    id: 'classic-blue',
    name: '经典蓝',
    colors: {
      primary: '#1890ff',
      secondary: '#e6f7ff',
      text: '#333333',
      heading: '#1f1f1f',
      background: '#ffffff',
      accent: '#096dd9',
    },
    styles: {
      h1: {
        fontSize: '22px',
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: '24px',
        marginTop: '10px',
        borderBottom: '2px solid #1890ff',
        paddingBottom: '10px',
        color: '#1f1f1f',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      h2: {
        fontSize: '18px',
        fontWeight: 'bold',
        marginBottom: '20px',
        marginTop: '30px',
        borderLeft: '4px solid #1890ff',
        paddingLeft: '10px',
        lineHeight: '1.4',
        color: '#1f1f1f',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      h3: {
        fontSize: '16px',
        fontWeight: 'bold',
        marginBottom: '16px',
        marginTop: '24px',
        color: '#1890ff',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      p: { ...baseText, color: '#3f3f3f' },
      blockquote: {
        borderLeft: '4px solid #1890ff',
        backgroundColor: '#f0f5ff',
        padding: '16px',
        color: '#595959',
        borderRadius: '4px',
        margin: '20px 0',
        fontSize: '15px',
        lineHeight: '1.6',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      list: baseList,
      li: { ...baseLi, color: '#3f3f3f' },
      code: {
        backgroundColor: '#f6f8fa',
        padding: '2px 4px',
        borderRadius: '4px',
        color: '#d73a49',
        fontFamily: 'Consolas, Monaco, monospace',
        fontSize: '14px',
      },
      link: {
        color: '#1890ff',
        textDecoration: 'none',
        borderBottom: '1px dashed #1890ff',
      },
      strong: {
        color: '#1890ff',
        fontWeight: 'bold',
      },
    },
  },
  {
    id: 'elegant-green',
    name: '清新绿',
    colors: {
      primary: '#07c160',
      secondary: '#f0f9eb',
      text: '#333333',
      heading: '#2c3e50',
      background: '#ffffff',
      accent: '#05964c',
    },
    styles: {
      h1: {
        fontSize: '24px',
        fontWeight: 'bold',
        marginBottom: '30px',
        marginTop: '10px',
        textAlign: 'center',
        color: '#07c160',
        borderBottom: '3px solid #96e6a1',
        paddingBottom: '10px',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      h2: {
        fontSize: '18px',
        fontWeight: 'bold',
        marginBottom: '20px',
        marginTop: '30px',
        display: 'inline-block',
        backgroundColor: '#f0f9eb',
        color: '#07c160',
        padding: '5px 15px',
        borderRadius: '20px',
        border: '1px solid #d4fc79',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      h3: {
        fontSize: '17px',
        fontWeight: 'bold',
        marginBottom: '16px',
        marginTop: '24px',
        color: '#2c3e50',
        paddingLeft: '8px',
        borderLeft: '4px solid #07c160',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      p: { ...baseText, color: '#2c3e50' },
      blockquote: {
        borderTop: '2px solid #07c160',
        borderBottom: '2px solid #07c160',
        backgroundColor: '#fff',
        padding: '20px',
        color: '#555',
        margin: '20px 0',
        position: 'relative',
        fontSize: '15px',
        textAlign: 'center',
        lineHeight: '1.6',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      list: { ...baseList, listStyleType: 'disc' },
      li: { ...baseLi, color: '#2c3e50' },
      code: {
        backgroundColor: '#fff5f5',
        padding: '2px 4px',
        borderRadius: '4px',
        color: '#c0392b',
        fontFamily: 'Consolas, Monaco, monospace',
        fontSize: '14px',
      },
      link: {
        color: '#07c160',
        textDecoration: 'none',
        fontWeight: 'bold',
        borderBottom: '1px solid #07c160',
      },
      strong: {
        color: '#07c160',
        fontWeight: 'bold',
      },
    },
  },
  {
    id: 'warm-orange',
    name: '暖阳橙',
    colors: {
      primary: '#fa8c16',
      secondary: '#fff7e6',
      text: '#4a4a4a',
      heading: '#d46b08',
      background: '#ffffff',
      accent: '#d46b08',
    },
    styles: {
      h1: {
        fontSize: '22px',
        fontWeight: 'bold',
        marginBottom: '24px',
        marginTop: '10px',
        textAlign: 'center',
        borderBottom: '3px solid #fa8c16',
        display: 'table',
        marginLeft: 'auto',
        marginRight: 'auto',
        padding: '0 10px 10px 10px',
        color: '#fa8c16',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      h2: {
        fontSize: '18px',
        fontWeight: 'bold',
        marginBottom: '20px',
        marginTop: '30px',
        color: '#ffffff',
        backgroundColor: '#fa8c16',
        padding: '8px 16px',
        borderRadius: '0 10px 10px 0',
        display: 'inline-block',
        borderRight: '3px solid #ffd591',
        borderBottom: '3px solid #ffd591',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      h3: {
        fontSize: '16px',
        fontWeight: 'bold',
        marginBottom: '16px',
        marginTop: '24px',
        color: '#d46b08',
        borderBottom: '1px solid #ffd591',
        paddingBottom: '4px',
        display: 'inline-block',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      p: { ...baseText, color: '#4a4a4a' },
      blockquote: {
        borderLeft: 'none',
        backgroundColor: '#fff7e6',
        padding: '20px',
        color: '#873800',
        borderRadius: '8px',
        margin: '20px 0',
        fontSize: '15px',
        border: '1px dashed #fa8c16',
        lineHeight: '1.6',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      list: baseList,
      li: { ...baseLi, color: '#4a4a4a' },
      code: {
        backgroundColor: '#fff0f6',
        padding: '2px 4px',
        borderRadius: '4px',
        color: '#c41d7f',
        fontFamily: 'Consolas, Monaco, monospace',
        fontSize: '14px',
      },
      link: {
        color: '#fa8c16',
        textDecoration: 'none',
        borderBottom: '1px solid #fa8c16',
      },
      strong: {
        color: '#fa8c16',
        fontWeight: 'bold',
      },
    },
  },
  {
    id: 'noble-purple',
    name: '高贵紫',
    colors: {
      primary: '#722ed1',
      secondary: '#f9f0ff',
      text: '#333333',
      heading: '#531dab',
      background: '#ffffff',
      accent: '#b37feb',
    },
    styles: {
      h1: {
        fontSize: '22px',
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: '24px',
        color: '#531dab',
        borderBottom: '3px solid #722ed1',
        paddingBottom: '10px',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      h2: {
        fontSize: '18px',
        fontWeight: 'bold',
        marginBottom: '20px',
        marginTop: '30px',
        color: '#fff',
        backgroundColor: '#722ed1',
        padding: '6px 20px',
        borderRadius: '50px 0 50px 0',
        display: 'inline-block',
        border: '2px solid #b37feb',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      h3: {
        fontSize: '16px',
        fontWeight: 'bold',
        marginTop: '24px',
        marginBottom: '16px',
        color: '#722ed1',
        paddingLeft: '10px',
        borderLeft: '4px solid #722ed1',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      p: { ...baseText, color: '#333' },
      blockquote: {
        backgroundColor: '#f9f0ff',
        borderLeft: '4px solid #722ed1',
        padding: '16px',
        margin: '20px 0',
        borderRadius: '0 8px 8px 0',
        color: '#531dab',
        fontSize: '15px',
        lineHeight: '1.6',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      list: baseList,
      li: { ...baseLi, color: '#333' },
      code: { 
          backgroundColor: '#f9f0ff', 
          color: '#722ed1', 
          padding: '2px 4px', 
          borderRadius: '4px', 
          fontFamily: 'Consolas, Monaco, monospace',
          fontSize: '14px',
      },
      link: { 
          color: '#722ed1', 
          textDecoration: 'none', 
          borderBottom: '1px solid #722ed1' 
      },
      strong: {
        color: '#722ed1',
        fontWeight: 'bold',
      },
    },
  },
  {
    id: 'minimalist-black',
    name: '极简黑',
    colors: {
      primary: '#000000',
      secondary: '#f5f5f5',
      text: '#222222',
      heading: '#000000',
      background: '#ffffff',
      accent: '#333333',
    },
    styles: {
      h1: {
        fontSize: '24px',
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: '30px',
        color: '#000',
        letterSpacing: '2px',
        borderTop: '2px solid #000',
        borderBottom: '2px solid #000',
        padding: '10px 20px',
        display: 'table',
        margin: '30px auto',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      h2: {
        fontSize: '18px',
        fontWeight: 'bold',
        marginBottom: '20px',
        marginTop: '30px',
        color: '#000',
        borderBottom: '3px solid #000',
        display: 'inline-block',
        paddingBottom: '4px',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      h3: {
        fontSize: '16px',
        fontWeight: 'bold',
        marginTop: '24px',
        marginBottom: '16px',
        backgroundColor: '#000',
        color: '#fff',
        padding: '4px 10px',
        display: 'inline-block',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      p: { ...baseText, color: '#222' },
      blockquote: {
        borderTop: '2px solid #000',
        borderBottom: '2px solid #000',
        padding: '20px',
        margin: '20px 0',
        color: '#444',
        textAlign: 'center',
        fontWeight: '500',
        backgroundColor: '#fff',
        fontSize: '15px',
        lineHeight: '1.6',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      list: { ...baseList, listStyleType: 'disc' },
      li: { ...baseLi, color: '#222' },
      code: { 
          backgroundColor: '#f0f0f0', 
          color: '#000', 
          padding: '2px 4px', 
          borderRadius: '2px', 
          fontFamily: 'Consolas, Monaco, monospace', 
          fontWeight: 'bold',
          fontSize: '14px',
      },
      link: { 
          color: '#000', 
          textDecoration: 'underline', 
          fontWeight: 'bold' 
      },
      strong: {
        color: '#000',
        fontWeight: 'bold',
        backgroundColor: '#f5f5f5',
        padding: '0 2px',
      },
    },
  },
  {
    id: 'sakura-pink',
    name: '樱花粉',
    colors: {
      primary: '#eb2f96',
      secondary: '#fff0f6',
      text: '#555555',
      heading: '#c41d7f',
      background: '#ffffff',
      accent: '#ffadd2',
    },
    styles: {
      h1: {
        fontSize: '22px',
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: '24px',
        color: '#c41d7f',
        backgroundColor: '#fff0f6',
        padding: '15px',
        borderRadius: '12px',
        border: '2px dashed #ffadd2',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      h2: {
        fontSize: '18px',
        fontWeight: 'bold',
        marginBottom: '20px',
        marginTop: '30px',
        color: '#c41d7f',
        borderLeft: '5px solid #ffadd2',
        borderBottom: '1px solid #fff0f6',
        padding: '5px 0 5px 12px',
        backgroundColor: '#fff0f6',
        borderRadius: '0 8px 8px 0',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      h3: {
        fontSize: '16px',
        fontWeight: 'bold',
        marginTop: '24px',
        marginBottom: '16px',
        color: '#eb2f96',
        borderBottom: '2px solid #ffadd2',
        paddingBottom: '4px',
        display: 'inline-block',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      p: { ...baseText, color: '#555' },
      blockquote: {
        backgroundColor: '#fff0f6',
        borderRadius: '12px',
        padding: '16px',
        margin: '20px 0',
        color: '#c41d7f',
        border: '2px dotted #ffadd2',
        fontSize: '15px',
        lineHeight: '1.6',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      list: baseList,
      li: { ...baseLi, color: '#555' },
      code: { 
          backgroundColor: '#fff0f6', 
          color: '#c41d7f', 
          padding: '2px 4px', 
          borderRadius: '4px', 
          fontFamily: 'Consolas, Monaco, monospace',
          fontSize: '14px',
      },
      link: { 
          color: '#eb2f96', 
          textDecoration: 'none', 
          borderBottom: '1px dotted #eb2f96' 
      },
      strong: {
        color: '#c41d7f',
        fontWeight: 'bold',
      },
    },
  },
  {
    id: 'chinese-red',
    name: '中国红',
    colors: {
      primary: '#c41d24',
      secondary: '#fdf2f2',
      text: '#2b1216',
      heading: '#c41d24',
      background: '#ffffff',
      accent: '#e6b8b8',
    },
    styles: {
      h1: {
        fontSize: '26px',
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: '30px',
        marginTop: '20px',
        color: '#c41d24',
        backgroundImage: 'linear-gradient(to right, #c41d24, #faad14)',
        backgroundClip: 'text',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        borderBottom: '2px solid #c41d24',
        paddingBottom: '10px',
        lineHeight: '1.4',
        fontFamily: SERIF_FONT_FAMILY,
      },
      h2: {
        fontSize: '20px',
        fontWeight: 'bold',
        marginBottom: '20px',
        marginTop: '32px',
        color: '#fff',
        backgroundColor: '#c41d24',
        padding: '8px 24px',
        borderRadius: '40px',
        display: 'inline-block',
        boxShadow: '0 2px 4px rgba(196, 29, 36, 0.2)',
        lineHeight: '1.4',
        fontFamily: SERIF_FONT_FAMILY,
      },
      h3: {
        fontSize: '17px',
        fontWeight: 'bold',
        marginTop: '24px',
        marginBottom: '16px',
        color: '#c41d24',
        paddingLeft: '12px',
        borderLeft: '4px solid #c41d24',
        lineHeight: '1.4',
        fontFamily: SERIF_FONT_FAMILY,
      },
      p: { ...baseText, color: '#2b1216', fontFamily: SERIF_FONT_FAMILY },
      blockquote: {
        backgroundColor: '#fff7f7',
        borderLeft: '4px solid #c41d24',
        padding: '16px 20px',
        margin: '20px 0',
        color: '#5c2b2f',
        fontSize: '15px',
        lineHeight: '1.8',
        fontStyle: 'italic',
        fontFamily: SERIF_FONT_FAMILY,
      },
      list: baseList,
      li: { ...baseLi, color: '#2b1216', fontFamily: SERIF_FONT_FAMILY },
      code: {
        backgroundColor: '#fff1f0',
        color: '#c41d24',
        padding: '2px 6px',
        borderRadius: '4px',
        fontFamily: MONO_FONT_FAMILY,
        fontSize: '14px',
      },
      link: {
        color: '#c41d24',
        textDecoration: 'none',
        borderBottom: '1px solid #c41d24',
      },
      strong: {
        color: '#c41d24',
        fontWeight: 'bold',
      },
    },
  },
  {
    id: 'tech-geek',
    name: '科技极客',
    colors: {
      primary: '#24292e',
      secondary: '#f6f8fa',
      text: '#24292e',
      heading: '#24292e',
      background: '#ffffff',
      accent: '#0366d6',
    },
    styles: {
      h1: {
        fontSize: '24px',
        fontWeight: 'bold',
        textAlign: 'left',
        marginBottom: '24px',
        marginTop: '10px',
        color: '#24292e',
        borderBottom: '1px solid #e1e4e8',
        paddingBottom: '10px',
        lineHeight: '1.4',
        fontFamily: MONO_FONT_FAMILY,
      },
      h2: {
        fontSize: '20px',
        fontWeight: 'bold',
        marginBottom: '20px',
        marginTop: '30px',
        color: '#24292e',
        display: 'flex',
        alignItems: 'center',
        lineHeight: '1.4',
        fontFamily: MONO_FONT_FAMILY,
        borderLeft: '6px solid #0366d6',
        paddingLeft: '12px',
      },
      h3: {
        fontSize: '17px',
        fontWeight: 'bold',
        marginTop: '24px',
        marginBottom: '16px',
        color: '#0366d6',
        lineHeight: '1.4',
        fontFamily: MONO_FONT_FAMILY,
      },
      p: { ...baseText, color: '#24292e' },
      blockquote: {
        borderLeft: '4px solid #dfe2e5',
        color: '#6a737d',
        padding: '0 1em',
        margin: '20px 0',
        backgroundColor: 'transparent',
        fontSize: '15px',
        lineHeight: '1.6',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      list: baseList,
      li: { ...baseLi, color: '#24292e' },
      code: {
        backgroundColor: 'rgba(27,31,35,0.05)',
        color: '#24292e',
        padding: '0.2em 0.4em',
        borderRadius: '3px',
        fontFamily: MONO_FONT_FAMILY,
        fontSize: '85%',
      },
      link: {
        color: '#0366d6',
        textDecoration: 'none',
      },
      strong: {
        color: '#24292e',
        fontWeight: 'bold',
      },
    },
  },
  {
    id: 'academic',
    name: '学术论文',
    colors: {
      primary: '#1b1f23',
      secondary: '#ffffff',
      text: '#000000',
      heading: '#000000',
      background: '#ffffff',
      accent: '#000000',
    },
    styles: {
      h1: {
        fontSize: '22px',
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: '30px',
        marginTop: '10px',
        color: '#000',
        lineHeight: '1.4',
        fontFamily: SERIF_FONT_FAMILY,
        textTransform: 'uppercase',
      },
      h2: {
        fontSize: '18px',
        fontWeight: 'bold',
        marginBottom: '15px',
        marginTop: '25px',
        color: '#000',
        textAlign: 'center',
        lineHeight: '1.4',
        fontFamily: SERIF_FONT_FAMILY,
        borderTop: '1px solid #000',
        borderBottom: '1px solid #000',
        padding: '5px 20px',
        display: 'inline-block',
      },
      h3: {
        fontSize: '16px',
        fontWeight: 'bold',
        marginTop: '20px',
        marginBottom: '10px',
        color: '#000',
        lineHeight: '1.4',
        fontFamily: SERIF_FONT_FAMILY,
        fontStyle: 'italic',
      },
      p: { 
        ...baseText, 
        color: '#000', 
        fontFamily: SERIF_FONT_FAMILY, 
        textIndent: '2em',
        marginBottom: '1em' 
      },
      blockquote: {
        borderLeft: '3px solid #000',
        padding: '10px 20px',
        margin: '20px 0',
        color: '#444',
        fontSize: '14px',
        lineHeight: '1.6',
        fontFamily: SERIF_FONT_FAMILY,
        fontStyle: 'italic',
      },
      list: baseList,
      li: { ...baseLi, color: '#000', fontFamily: SERIF_FONT_FAMILY },
      code: {
        backgroundColor: '#f0f0f0',
        color: '#000',
        padding: '2px 4px',
        borderRadius: '2px',
        fontFamily: MONO_FONT_FAMILY,
        fontSize: '14px',
        fontStyle: 'normal',
      },
      link: {
        color: '#000',
        textDecoration: 'underline',
      },
      strong: {
        color: '#000',
        fontWeight: 'bold',
      },
    },
  },
  {
    id: 'macaroon',
    name: '马卡龙',
    colors: {
      primary: '#ff9c6e',
      secondary: '#fff7e6',
      text: '#595959',
      heading: '#ff7a45',
      background: '#ffffff',
      accent: '#bae7ff',
    },
    styles: {
      h1: {
        fontSize: '22px',
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: '24px',
        marginTop: '10px',
        color: '#ff7a45',
        backgroundColor: '#fff7e6',
        border: '2px solid #ffc069',
        borderRadius: '20px',
        padding: '10px 20px',
        lineHeight: '1.4',
        fontFamily: 'Quicksand, "Microsoft YaHei", sans-serif',
        boxShadow: '3px 3px 0px #bae7ff',
      },
      h2: {
        fontSize: '18px',
        fontWeight: 'bold',
        marginBottom: '20px',
        marginTop: '30px',
        color: '#ff7a45',
        backgroundColor: '#e6f7ff',
        padding: '8px 16px',
        borderRadius: '12px',
        display: 'inline-block',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      h3: {
        fontSize: '16px',
        fontWeight: 'bold',
        marginTop: '24px',
        marginBottom: '16px',
        color: '#9254de',
        borderBottom: '2px dashed #d3adf7',
        paddingBottom: '4px',
        display: 'inline-block',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      p: { ...baseText, color: '#595959' },
      blockquote: {
        backgroundColor: '#fff1b8',
        borderRadius: '16px',
        padding: '20px',
        margin: '20px 0',
        color: '#d48806',
        fontSize: '15px',
        lineHeight: '1.6',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      list: baseList,
      li: { ...baseLi, color: '#595959' },
      code: {
        backgroundColor: '#fff0f6',
        color: '#eb2f96',
        padding: '2px 6px',
        borderRadius: '8px',
        fontFamily: MONO_FONT_FAMILY,
        fontSize: '14px',
      },
      link: {
        color: '#36cfc9',
        textDecoration: 'none',
        borderBottom: '2px solid #b5f5ec',
      },
      strong: {
        color: '#ff7a45',
        fontWeight: 'bold',
      },
    },
  },
  {
    id: 'magazine',
    name: '杂志风',
    colors: {
      primary: '#2f3640',
      secondary: '#f5f6fa',
      text: '#2f3640',
      heading: '#2f3640',
      background: '#ffffff',
      accent: '#e1b12c',
    },
    styles: {
      h1: {
        fontSize: '28px',
        fontWeight: '900',
        textAlign: 'left',
        marginBottom: '30px',
        marginTop: '10px',
        color: '#2f3640',
        lineHeight: '1.2',
        fontFamily: '"Impact", "Arial Black", sans-serif',
        textTransform: 'uppercase',
        letterSpacing: '-1px',
      },
      h2: {
        fontSize: '20px',
        fontWeight: 'bold',
        marginBottom: '24px',
        marginTop: '40px',
        color: '#ffffff',
        backgroundColor: '#2f3640',
        padding: '10px 20px',
        display: 'inline-block',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
        transform: 'skew(-5deg)',
        boxShadow: '5px 5px 0 #e1b12c',
      },
      h3: {
        fontSize: '18px',
        fontWeight: 'bold',
        marginTop: '24px',
        marginBottom: '16px',
        color: '#2f3640',
        borderLeft: '8px solid #e1b12c',
        paddingLeft: '12px',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      p: { ...baseText, color: '#2f3640', fontSize: '17px' },
      blockquote: {
        borderTop: '2px solid #2f3640',
        borderBottom: '2px solid #2f3640',
        padding: '30px 20px',
        margin: '30px 0',
        color: '#2f3640',
        fontSize: '18px',
        lineHeight: '1.6',
        fontFamily: SERIF_FONT_FAMILY,
        textAlign: 'center',
        fontWeight: 'bold',
      },
      list: baseList,
      li: { ...baseLi, color: '#2f3640', fontSize: '17px' },
      code: {
        backgroundColor: '#2f3640',
        color: '#e1b12c',
        padding: '2px 6px',
        fontFamily: MONO_FONT_FAMILY,
        fontSize: '14px',
        fontWeight: 'bold',
      },
      link: {
        color: '#e1b12c',
        textDecoration: 'none',
        fontWeight: 'bold',
        backgroundColor: '#2f3640',
        padding: '0 4px',
      },
      strong: {
        color: '#2f3640',
        fontWeight: '900',
        textDecoration: 'underline',
        textDecorationColor: '#e1b12c',
        textDecorationThickness: '4px',
      },
    },
  },
  // --- HIGH-END TECH THEMES (REPLACEMENT) ---
  {
    id: 'modern-geist',
    name: 'Modern Geist',
    colors: {
      primary: '#000000',
      secondary: '#eaeaea',
      text: '#333333',
      heading: '#000000',
      background: '#ffffff',
      accent: '#0070f3', // Vercel Blue
    },
    styles: {
      h1: {
        fontSize: '28px',
        fontWeight: '800',
        textAlign: 'left',
        marginBottom: '30px',
        marginTop: '20px',
        color: '#000',
        letterSpacing: '-0.05em', // Tight tracking
        lineHeight: '1.2',
        fontFamily: '"Inter", "Helvetica Neue", Arial, sans-serif',
        borderBottom: 'none',
      },
      h2: {
        fontSize: '22px',
        fontWeight: '700',
        marginBottom: '20px',
        marginTop: '40px',
        color: '#000',
        letterSpacing: '-0.03em',
        lineHeight: '1.3',
        fontFamily: '"Inter", "Helvetica Neue", Arial, sans-serif',
        display: 'flex',
        alignItems: 'center',
      },
      h3: {
        fontSize: '18px',
        fontWeight: '600',
        marginTop: '24px',
        marginBottom: '16px',
        color: '#000',
        lineHeight: '1.4',
        fontFamily: '"Inter", "Helvetica Neue", Arial, sans-serif',
      },
      p: { 
        ...baseText, 
        color: '#444', 
        fontFamily: '"Inter", "Helvetica Neue", Arial, sans-serif',
        fontSize: '16px',
        lineHeight: '1.8'
      },
      blockquote: {
        borderLeft: '2px solid #000',
        padding: '0 20px',
        margin: '30px 0',
        color: '#666',
        fontSize: '16px',
        lineHeight: '1.7',
        fontFamily: '"Inter", "Helvetica Neue", Arial, sans-serif',
        fontStyle: 'italic',
        backgroundColor: 'transparent', // Minimalist
      },
      list: { ...baseList, listStyleType: 'disc' },
      li: { ...baseLi, color: '#444', fontFamily: '"Inter", "Helvetica Neue", Arial, sans-serif' },
      code: {
        backgroundColor: '#f5f5f5',
        color: '#eb5757', // Subtle red
        padding: '2px 6px',
        borderRadius: '4px',
        fontFamily: '"Menlo", "Monaco", monospace', // Clean mono
        fontSize: '13px',
      },
      link: {
        color: '#0070f3', // Vercel Blue
        textDecoration: 'none',
        borderBottom: '1px solid rgba(0,112,243,0.3)',
        transition: 'all 0.2s',
      },
      strong: {
        color: '#000',
        fontWeight: '700',
      },
    },
  },
  {
    id: 'linear-glow',
    name: 'Linear Glow',
    colors: {
      primary: '#5E6AD2', // Linear Purple
      secondary: '#F7F8F9',
      text: '#2E3138', // Dark Slate
      heading: '#1A1C20',
      background: '#ffffff',
      accent: '#8792E3',
    },
    styles: {
      h1: {
        fontSize: '26px',
        fontWeight: '700',
        textAlign: 'center',
        marginBottom: '30px',
        marginTop: '20px',
        color: '#1A1C20',
        lineHeight: '1.3',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      h2: {
        fontSize: '20px',
        fontWeight: '600',
        marginBottom: '20px',
        marginTop: '36px',
        color: '#5E6AD2', // Purple Brand
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
        display: 'inline-block',
        background: 'linear-gradient(90deg, rgba(94,106,210,0.1) 0%, rgba(255,255,255,0) 100%)',
        padding: '6px 16px 6px 12px',
        borderRadius: '4px',
        borderLeft: '3px solid #5E6AD2',
      },
      h3: {
        fontSize: '17px',
        fontWeight: '600',
        marginTop: '24px',
        marginBottom: '12px',
        color: '#1A1C20',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      p: { ...baseText, color: '#3F4350' }, // Softer black
      blockquote: {
        background: 'rgba(94,106,210,0.04)', // Very subtle purple tint
        borderRadius: '8px',
        padding: '20px',
        margin: '24px 0',
        color: '#5E6AD2',
        fontSize: '15px',
        lineHeight: '1.6',
        fontFamily: WECHAT_FONT_FAMILY,
        border: '1px solid rgba(94,106,210,0.1)',
      },
      list: baseList,
      li: { ...baseLi, color: '#3F4350' },
      code: {
        backgroundColor: '#F7F8F9',
        color: '#5E6AD2',
        padding: '2px 6px',
        borderRadius: '6px',
        fontFamily: 'Consolas, monospace',
        fontSize: '14px',
        border: '1px solid #E8EAEF',
      },
      link: {
        color: '#5E6AD2',
        textDecoration: 'none',
        fontWeight: '500',
        borderBottom: '1px solid rgba(94,106,210,0.3)',
      },
      strong: {
        color: '#1A1C20',
        fontWeight: '700',
      },
    },
  },
  {
    id: 'titanium-grey',
    name: 'Titanium',
    colors: {
      primary: '#1d1d1f', // Apple Black
      secondary: '#f5f5f7', // Apple Light Grey
      text: '#1d1d1f',
      heading: '#1d1d1f',
      background: '#ffffff',
      accent: '#2997ff', // Apple Blue
    },
    styles: {
      h1: {
        fontSize: '26px',
        fontWeight: '600',
        textAlign: 'center',
        marginBottom: '40px',
        marginTop: '20px',
        color: '#1d1d1f',
        lineHeight: '1.3',
        fontFamily: WECHAT_FONT_FAMILY,
        letterSpacing: '-0.02em',
      },
      h2: {
        fontSize: '20px',
        fontWeight: '600',
        marginBottom: '24px',
        marginTop: '40px',
        color: '#1d1d1f',
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
        paddingBottom: '8px',
        borderBottom: '1px solid #e5e5e5', // Very subtle separator
      },
      h3: {
        fontSize: '17px',
        fontWeight: '600',
        marginTop: '28px',
        marginBottom: '16px',
        color: '#484848', // Slightly lighter for hierarchy
        lineHeight: '1.4',
        fontFamily: WECHAT_FONT_FAMILY,
      },
      p: { ...baseText, color: '#3a3a3c', fontSize: '16px', lineHeight: '1.8' },
      blockquote: {
        borderLeft: 'none',
        padding: '0 20px',
        margin: '30px 0',
        color: '#86868b', // Apple Grey
        fontSize: '18px', // Larger quote
        lineHeight: '1.5',
        fontFamily: WECHAT_FONT_FAMILY,
        fontWeight: '500',
        textAlign: 'center',
      },
      list: baseList,
      li: { ...baseLi, color: '#3a3a3c' },
      code: {
        backgroundColor: 'rgba(0,0,0,0.04)',
        color: '#1d1d1f',
        padding: '2px 6px',
        borderRadius: '4px',
        fontFamily: 'SF Mono, Menlo, monospace',
        fontSize: '13px',
      },
      link: {
        color: '#0066cc', // Classic Link Blue
        textDecoration: 'none',
      },
      strong: {
        color: '#1d1d1f',
        fontWeight: '700',
      },
    },
  },
];
